[package]
name = "galvanic-assert"
version = "0.5.0"
authors = ["Christopher Bacher <mindsbackyard@gmail.com>"]

description = "A comprehensive set of matcher-based assertions for easier testing"

homepage = "https://github.com/mindsbackyard/galvanic-assert"
repository = "https://github.com/mindsbackyard/galvanic-assert"
documentation = "https://docs.rs/galvanic-assert"

readme = "Readme.md"

license = "Apache-2.0"

keywords = ["test", "assert", "matching", "fluent"]
categories = ["development-tools::testing"]

[dependencies]
